version: '3.8'
services:
  ciencias:
    image: postgres:15-alpine
    container_name: ciencias
    restart: always
    environment:
      POSTGRES_PASSWORD: postgres
      POSTGRES_USER: postgres
      POSTGRES_DB: universidad
    ports:
      - "5434:5432"
    volumes:
      - ciencias-data:/var/lib/postgresql/data
      - ./scripts/common:/common
      - ./scripts/ciencias_scripts:/docker-entrypoint-initdb.d/
      - ./data:/csv-data:ro
    networks:
      - pg-distributed
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 30s
      timeout: 10s
      retries: 3


  ingenieria:
    image: postgres:15-alpine
    container_name: ingenieria
    restart: always
    environment:
      POSTGRES_PASSWORD: postgres
      POSTGRES_USER: postgres
      POSTGRES_DB: universidad
    ports:
      - "5433:5432"
    volumes:
      - ingenieria-data:/var/lib/postgresql/data
      - ./scripts/common:/common
      - ./scripts/ingenieria_scripts:/docker-entrypoint-initdb.d/
      - ./data:/csv-data:ro
    networks:
      - pg-distributed
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 30s
      timeout: 10s
      retries: 3

  medioambiente:
    image: postgres:15-alpine
    container_name: medioambiente
    restart: always
    environment:
      POSTGRES_PASSWORD: postgres
      POSTGRES_USER: postgres
      POSTGRES_DB: universidad
    ports:
      - "5435:5432"
    volumes:
      - medioambiente-data:/var/lib/postgresql/data
      - ./scripts/common:/common
      - ./scripts/medioambiente_scripts:/docker-entrypoint-initdb.d/
      - ./data:/csv-data:ro
    networks:
      - pg-distributed
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 30s
      timeout: 10s
      retries: 3      

volumes:
  ciencias-data:
      driver: local
  ingenieria-data:
      driver: local
  medioambiente-data:
      driver: local

networks:
  pg-distributed:
    driver: bridge
    ipam:
      config:
        - subnet: 172.20.0.0/16